name: aim
channel_priority: strict
channels:
  - pytorch
  - nvidia
  - xformers
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy==1.26.4
  - pytorch==2.3.1
  - torchvision==0.18.1
  - torchmetrics==1.4.0
  - faiss-gpu==1.8.0
  - opencv==4.10.0
  - ffmpeg==4.2.2
  - einops==0.8.0
  - json5==0.9.6
  - timm==1.0.11
  - sentencepiece==0.2.0
  - diffusers==0.32.1
  - accelerate==1.2.1
  - matplotlib==3.9.2
  - scikit-learn==1.5.1
  - scikit-image==0.24.0
  - pandas==2.2.2
  - moviepy==1.0.3
  - configargparse==1.7
  - selenium==4.24.0
  - rclone==1.68.1
  - orjson==3.10.10
  - google-api-python-client==2.147.0
  - google-auth-httplib2==0.2.0
  - google-auth-oauthlib==0.5.2
  - pip
  - pip:
    - scenedetect==0.6.4
    - pytubefix==9.0.1
    - mmcv==1.3.9
    - openai==1.37.1
    - httpx==0.27.2
    - nltk==3.8.1
    - flash-attn==2.6.3
    - rclone-python==0.1.12
    - transformers==4.44.2
    - git+https://github.com/IDEA-Research/GroundingDINO.git
    - git+https://github.com/facebookresearch/segment-anything.git
    - git+https://github.com/IDEA-Research/Grounded-SAM-2.git
    - git+https://github.com/ViTAE-Transformer/ViTPose.git
